name: rambu_id
description: "RambuID: Aplikasi Pengenalan Rambu Jalan Raya Indonesia."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  camera_android: ^0.10.10+2
  camera: ^0.10.4
  camera_web: ^0.3.5
  flutter_map: ^8.1.1
  google_maps_flutter: ^2.12.1
  google_mlkit_object_detection: ^0.15.0
  tflite_flutter: ^0.11.0
  google_mlkit_image_labeling: ^0.14.1
  google_ml_kit: ^0.20.0
  provider: ^6.1.4
  bloc: ^9.0.0
  riverpod: ^2.6.1
  flutter_animate: ^4.5.2
  flutter_neumorphic: ^3.2.0
  getwidget: ^6.0.0
  flutter_local_notifications: ^19.1.0
  path_provider: ^2.1.5
  tflite_flutter_helper_plus: ^0.0.2
  image: ^3.3.0
  #tflite_flutter_helper: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model/rambu_model.tflite
    - assets/model/labels.txt
    
